# Papers in the dissertation {#sec-linked-papers .unnumbered}

## Study I

Isaksen AA, Sandbæk A, Bjerg L. Validation of Register-Based Diabetes Classifiers in Danish Data. *Clinical Epidemiology*. 2023;15:569-581. <https://doi.org/10.2147/CLEP.S407019>

## Study II

Isaksen AA, Sandbæk A, Skriver MV, Andersen GS, Bjerg L (2023) Guideline-level monitoring, biomarker levels and pharmacological treatment in migrants and native Danes with type 2 diabetes: Population-wide analyses. PLOS Global Public Health 3(10): e0001277 <https://doi.org/10.1371/journal.pgph.0001277>

## Study III

Isaksen, AA, Sandbæk, A, Skriver, MV, Bjerg, L. Glucose-lowering drug use in migrants and native Danes with type 2 diabetes: Disparities in combination therapy and drug types. *Diabetes Obesity and Metabolism*. 2023; 1-10. <https://doi.org/10.1111/dom.15230>

```{=tex}
\newpage

{\let\clearpage\relax \tableofcontents} 

\listoffigures

\listoftables
```


1 Continuous Glucose Monitoring–Derived Metrics and Cardiovascular Risk Among People with Diabetes: A Systematic Scoping Review (accepted, JMIR Diabetes)
PubMed and Embase were searched for studies examining associations between CGM data and clinical or subclinical CVD, and for studies assessing the predictive value of CGM data for CVD outcomes. Study selection and data extraction were performed according to predefined criteria following the PRISMA-Sc-r checklist, and findings were summarized descriptively.
2 Racial Disparities in Continuous Glucose Monitoring-Based 60-min Glucose Predictions Among People with Type 1 Diabetes (published, PLOS Digital Health)
Investigating racial group-fairness in blood glucose forecasting using machine learning models ina US dataset containing 205 participants with self identified (non-Hispanic White or non-Hispanic Black) ethnicity and race. Model performance and fairness was compared across groups using linear mixed effect models and root mean squarred errors.
3 Evaluation of a CGM Foundation Model for NT-proBNP Prediction and Embedding Space Analysis (work in progress)
This study evaluates representations from the CGMformer in populations with type 1 and type 2 diabetes. Embedding space structure was explored using UMAPs and cosine similarity distances, and the predictive value of CGM data for binary NT-proBNP status was assessed using logistic regression models.
