# Supervisors and Assessment Committee {.unnumbered}

#### PhD student:

**Helene Bei Thomsen**\
Department of Public Health, Aarhus University, Denmark

#### Supervisors:

**Associate Professor Adam Hulman, PhD (main supervisor)**\
Department of Public Health, Aarhus University, Denmark\
Steno Diabetes Center Aarhus, Aarhus university Hospital Denmark\

**Anders Aasted Isaksen, MD, PhD**\
Steno Diabetes Center Aarhus, Denmark\

**Guy Fagherazzi, PhD**\
Director of the Department of Precision Health\
Head of the Deep Digital Phenotyping Research Unit\
Luxembourg Institute of Health, Luxembourg\

**Signe Toft Andersen, MD, PhD**\
Steno Diabetes Center Aarhus, Denmark\
Gødstrup Hospital, Denmark

#### Assessment committee:

**Associate Professor Simon Tilma Vistisen (chairman)**\
Department of Clinical Medicine, Aarhus University, Denmark\
<!-- Email: vistisen@clin.au.dk -->

**Professor Cristina Soguero-Ruíz**\
Department of Signal Theory and Communications, King Juan Carlos University, Spain\
<!-- Email: cristina.soguero@urjc.es -->

**Associate Professor Simon Lebech Cichosz**\
Department of Health Science and Technology, The Faculty of Medicine, Medical\
Informatics and Image Analysis, Aalborg University, Denmark\
<!-- Email: simcich@hst.aau.dk -->
