<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Methods – Machine learning methods for continuous glucose monitoring data and their potential in cardiovascular risk assessment</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./4-results.html" rel="next">
<link href="./2-aims.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-82cb5808e81da3454e8042d903791e03.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
main.content {
  text-align: justify;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./3-methods.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Methods</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Machine learning methods for continuous glucose monitoring data and their potential in cardiovascular risk assessment</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cover Page</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0-papers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Papers in the dissertation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0-abbreviations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abbreviations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-aims.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Aims</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-methods.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Results</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-discussion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Discussion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-conclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app1-supplementary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Study I: Search strings</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview-of-studies" id="toc-overview-of-studies" class="nav-link active" data-scroll-target="#overview-of-studies"><span class="header-section-number">3.1</span> Overview of Studies</a></li>
  <li><a href="#scoping-review-methodology" id="toc-scoping-review-methodology" class="nav-link" data-scroll-target="#scoping-review-methodology"><span class="header-section-number">3.2</span> Scoping Review Methodology</a>
  <ul class="collapse">
  <li><a href="#sec-concepts" id="toc-sec-concepts" class="nav-link" data-scroll-target="#sec-concepts"><span class="header-section-number">3.2.1</span> Concepts and Definitions</a></li>
  <li><a href="#search-and-selection-of-sources" id="toc-search-and-selection-of-sources" class="nav-link" data-scroll-target="#search-and-selection-of-sources"><span class="header-section-number">3.2.2</span> Search and Selection of Sources</a></li>
  <li><a href="#data-charting-process-and-data-items" id="toc-data-charting-process-and-data-items" class="nav-link" data-scroll-target="#data-charting-process-and-data-items"><span class="header-section-number">3.2.3</span> Data Charting Process and Data Items</a></li>
  <li><a href="#synthesis-of-results" id="toc-synthesis-of-results" class="nav-link" data-scroll-target="#synthesis-of-results"><span class="header-section-number">3.2.4</span> Synthesis of Results</a></li>
  </ul></li>
  <li><a href="#study-populations" id="toc-study-populations" class="nav-link" data-scroll-target="#study-populations"><span class="header-section-number">3.3</span> Study Populations</a>
  <ul class="collapse">
  <li><a href="#cancan-data" id="toc-cancan-data" class="nav-link" data-scroll-target="#cancan-data"><span class="header-section-number">3.3.1</span> CANCAN Data</a></li>
  <li><a href="#t1d-exchange-data" id="toc-t1d-exchange-data" class="nav-link" data-scroll-target="#t1d-exchange-data"><span class="header-section-number">3.3.2</span> T1D Exchange Data</a></li>
  </ul></li>
  <li><a href="#foundation-models-and-predictive-utility-of-cgm-data" id="toc-foundation-models-and-predictive-utility-of-cgm-data" class="nav-link" data-scroll-target="#foundation-models-and-predictive-utility-of-cgm-data"><span class="header-section-number">3.4</span> Foundation Models and Predictive Utility of CGM data</a>
  <ul class="collapse">
  <li><a href="#data-and-participant-selection" id="toc-data-and-participant-selection" class="nav-link" data-scroll-target="#data-and-participant-selection"><span class="header-section-number">3.4.1</span> Data and Participant Selection</a></li>
  <li><a href="#transfer-learning-foundation-models-and-embeddings" id="toc-transfer-learning-foundation-models-and-embeddings" class="nav-link" data-scroll-target="#transfer-learning-foundation-models-and-embeddings"><span class="header-section-number">3.4.2</span> Transfer Learning, Foundation Models and Embeddings</a></li>
  </ul></li>
  <li><a href="#cardiovascular-risk-assessment" id="toc-cardiovascular-risk-assessment" class="nav-link" data-scroll-target="#cardiovascular-risk-assessment"><span class="header-section-number">3.5</span> Cardiovascular Risk Assessment</a>
  <ul class="collapse">
  <li><a href="#predictors" id="toc-predictors" class="nav-link" data-scroll-target="#predictors"><span class="header-section-number">3.5.1</span> Predictors</a></li>
  <li><a href="#model-development-and-evaluation" id="toc-model-development-and-evaluation" class="nav-link" data-scroll-target="#model-development-and-evaluation"><span class="header-section-number">3.5.2</span> Model Development and Evaluation</a></li>
  <li><a href="#prediction-scheme-overview" id="toc-prediction-scheme-overview" class="nav-link" data-scroll-target="#prediction-scheme-overview"><span class="header-section-number">3.5.3</span> Prediction Scheme Overview</a></li>
  </ul></li>
  <li><a href="#algorithmic-fairness-and-blood-glucose-prediction" id="toc-algorithmic-fairness-and-blood-glucose-prediction" class="nav-link" data-scroll-target="#algorithmic-fairness-and-blood-glucose-prediction"><span class="header-section-number">3.6</span> Algorithmic Fairness and Blood Glucose Prediction</a>
  <ul class="collapse">
  <li><a href="#preprocessing-of-cgm-data-for-forecasting" id="toc-preprocessing-of-cgm-data-for-forecasting" class="nav-link" data-scroll-target="#preprocessing-of-cgm-data-for-forecasting"><span class="header-section-number">3.6.1</span> Preprocessing of CGM data for Forecasting</a></li>
  <li><a href="#partitioning-of-the-dataset" id="toc-partitioning-of-the-dataset" class="nav-link" data-scroll-target="#partitioning-of-the-dataset"><span class="header-section-number">3.6.2</span> Partitioning of the Dataset</a></li>
  <li><a href="#model-selection-and-training-approaches" id="toc-model-selection-and-training-approaches" class="nav-link" data-scroll-target="#model-selection-and-training-approaches"><span class="header-section-number">3.6.3</span> Model Selection and Training Approaches</a></li>
  <li><a href="#model-evaluation" id="toc-model-evaluation" class="nav-link" data-scroll-target="#model-evaluation"><span class="header-section-number">3.6.4</span> Model Evaluation</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-methods" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Methods</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this chapter the three studies included in this PhD will be presented together with a description of the datasets and methods used in the studies.</p>
<section id="overview-of-studies" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="overview-of-studies"><span class="header-section-number">3.1</span> Overview of Studies</h2>
<p>This dissertation includes three studies which are summarized in <a href="#tbl-overview-studies" class="quarto-xref">Table&nbsp;<span>3.1</span></a>.</p>
<div id="tbl-overview-studies" class="quarto-float quarto-figure quarto-figure-center anchored" data-bl-lines="rows">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-overview-studies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.1: Overview of the included studies
</figcaption>
<div aria-describedby="tbl-overview-studies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Study I</th>
<th style="text-align: left;">Study II</th>
<th style="text-align: left;">Study III</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Title</td>
<td style="text-align: left;">Continuous Glucose Monitoring–Derived Metrics and Cardiovascular Risk Among People With Diabetes: Systematic Scoping Review</td>
<td style="text-align: left;">Foundation model–derived representations of continuous glucose monitoring data: relation to glycemic patterns and cardiovascular risk</td>
<td style="text-align: left;">Racial disparities in continuous glucose monitoring-based 60-min glucose predictions among people with type 1 diabetes</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Study Type</td>
<td style="text-align: left;">Review</td>
<td style="text-align: left;"><a href="#acronyms_CGM">continuous glucose monitoring (CGM)</a> foundation model evaluation study</td>
<td style="text-align: left;">Algorithmic fairness study</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Data Sources</td>
<td style="text-align: left;">Literature on Embase and MEDLINE</td>
<td style="text-align: left;">The CANCAN study and the <a href="#acronyms_T1DX">T1D Exchange (T1DX)</a> dataset</td>
<td style="text-align: left;"><a href="#acronyms_T1DX">T1DX</a> dataset</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Population</td>
<td style="text-align: left;">Studies including people with type 1 diabetes, type 2 diabetes and/or prediabetes</td>
<td style="text-align: left;">159 people with type 2 diabetes 205 people with type 1 Diabetes</td>
<td style="text-align: left;">205 people with type 1 Diabetes</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Input, predictors and exposures</td>
<td style="text-align: left;">Search strategy and eligibility criteria</td>
<td style="text-align: left;">Clinical variables, CGM-derived metrics and CGM data</td>
<td style="text-align: left;">CGM data</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outcome, target</td>
<td style="text-align: left;">All studies that uses CGM data to investigate cardiovascular disease risks and outcomes</td>
<td style="text-align: left;">Visualization of foundation model embeddings and elevated NT-proBNP prediction</td>
<td style="text-align: left;">60-minute glucose prediction</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Analysis</td>
<td style="text-align: left;">Systematic scoping review, study characterization, and narrative synthesis</td>
<td style="text-align: left;">Foundation models and logistic regression models</td>
<td style="text-align: left;">long short term memory model (LSTM) and <a href="#acronyms_LMEM">linear mixed effect model (LMEM)</a></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="scoping-review-methodology" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="scoping-review-methodology"><span class="header-section-number">3.2</span> Scoping Review Methodology</h2>
<p>A scoping review was conducted to investigate current knowledge of CGM-data and its possible connection and predictive power to clinical and subclinical cardiovascular outcomes. Given the expected heterogeneity between studies and the broad exploratory nature of the research question, a scoping review was considered the most appropriate methodology, as the aim was to map the existing evidence within this field.<span class="citation" data-cites="Tricco2018"><sup><a href="references.html#ref-Tricco2018" role="doc-biblioref">1</a></sup></span> The scoping review followed the Manual for Evidence Synthesis (Chapter 10 - Scoping reviews) from the Joanna Briggs Institute (JBI) and reported according to the Preferred Reporting Items for Systematic Reviews and Meta-analyses extension for scoping review (PRISMA-ScR) guidelines.<span class="citation" data-cites="Tricco2018 Peters2024"><sup><a href="references.html#ref-Tricco2018" role="doc-biblioref">1</a>,<a href="references.html#ref-Peters2024" role="doc-biblioref">2</a></sup></span></p>
<section id="sec-concepts" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="sec-concepts"><span class="header-section-number">3.2.1</span> Concepts and Definitions</h3>
<p>The review focused exclusively on studies using CGM data as input for analyses of associations with, or prediction of, <a href="#acronyms_CVD">cardiovascular disease (CVD)</a>. This meant that studies only investigating self-monitored blood glucose with finger-prick measurements or blood sample measurements such as HbA1c were not considered in this review. CVD outcomes were divided into subclinical or clinical. For the clinical CVD, the following outcomes were considered: cardiovascular mortality, major adverse cardiovascular events, coronary artery disease, heart failure, stroke, and peripheral artery disease with synonymous terms included (e.g., ischemic heart diseases) and also clinical events (e.g., undergoing coronary artery bypass surgery). Subclinical CVD was grouped into six subcategories: arterial stiffness, flow resistance, arterial wall thickness, arterial wall composition, cardiac and pulse-related measures, and arterial lumen. CVD outcomes did not include broader risk factors nonspecific to cardiovascular risk (e.g., age or sex). Eligibility criterias for the scoping review<span class="citation" data-cites="Thomsen2026"><sup><a href="references.html#ref-Thomsen2026" role="doc-biblioref">3</a></sup></span> (Study I) can be found in <a href="#tbl-study1-eligibility-criteria" class="quarto-xref">Table&nbsp;<span>3.2</span></a>.</p>
<div id="tbl-study1-eligibility-criteria" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-study1-eligibility-criteria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.2: Eligibility criteria for the scoping review (Study I)
</figcaption>
<div aria-describedby="tbl-study1-eligibility-criteria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Inclusion Criteria</th>
<th>Exclusion Criteria</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Human clinical studies including participants with prediabetes or any type of diabetes except for gestational diabetes, regardless of definitions</td>
<td>Review articles, editorials, case reports, protocols, conference abstracts, and preprints.</td>
</tr>
<tr class="even">
<td>Peer-reviewed published original articles (including brief reports).</td>
<td>Animal studies not including any human participants.</td>
</tr>
<tr class="odd">
<td>Studies investigating either:</td>
<td>Studies not including metrics derived from <a href="#acronyms_CGM">CGM</a> device data</td>
</tr>
<tr class="even">
<td>a) The association between CGM-derived metrics of glycemic control and cardiovascular risk markers or cardiovascular diseases (prevalent or incident).</td>
<td>Studies including CGM-derived metrics as outcomes.</td>
</tr>
<tr class="odd">
<td>b) CGM-derived metrics of glycemic control as predictors of cardiovascular risk markers or cardiovascular diseases (prevalent or incident).</td>
<td>Studies not focusing on CVD outcomes according to our definition, as outlined in <a href="#sec-concepts" class="quarto-xref"><span>Section 3.2.1</span></a>.</td>
</tr>
<tr class="even">
<td></td>
<td>Studies focusing on pregnant women with any form of diabetes including gestational diabetes.</td>
</tr>
<tr class="odd">
<td></td>
<td>Studies where participants were monitored post-surgery or during hospitalization (e.g.&nbsp;Intensive care unit).</td>
</tr>
<tr class="even">
<td></td>
<td>Language not understood by authors</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="search-and-selection-of-sources" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="search-and-selection-of-sources"><span class="header-section-number">3.2.2</span> Search and Selection of Sources</h3>
<p>MEDLINE and Embase were searched from inception to March 11, 2025. The two databases were selected because they are core databases for biomedical literature. Owing to the resources available to the review team, the search could not be extended to additional databases. The search strategy was developed in collaboration with information specialists. An exploratory search was held and 13 studies within the field was identified and used to test the search strategy by ensuring the 13 identified studies were included in the final search string.<span class="citation" data-cites="Foreman2021 Yapanis2022 Helleputte2022 Lu2021 Martinez2021 Mita2023 Lu2020 Mo2013 Wakasugi2021 Magri2018 Su2011 Tang2016 Zhang2013"><sup><a href="references.html#ref-Foreman2021" role="doc-biblioref">4</a>–<a href="references.html#ref-Zhang2013" role="doc-biblioref">16</a></sup></span>. The search strategy was wished to be kept broad as it was known beforehand that the field contained inconsistent terminology and overlapping search categories (e.g., ‘blood glucose monitoring’ and ‘glycemic control’ both encompass finger-prick measurements) in order to ensure identification of all the relevant studies in MEDLINE and Embase. The full search strategy can be found in <a href="app1-supplementary.html" class="quarto-xref"><span>Appendix A</span></a>.</p>
<p>All identified records were uploaded into EPPI reviewer 6<span class="citation" data-cites="Thomas2023"><sup><a href="references.html#ref-Thomas2023" role="doc-biblioref">17</a></sup></span> and duplicates were removed. Titles and abstracts were screened by at least two independent reviewers and a meeting was held after ~5% of the titles and abstracts had been screened, to resolve disagreements and ensure consistency between reviewers. Afterwards full-text screening was performed by two independent reviewers and held up against eligibility criteria. Disagreements were resolved through discussion at physical meetings between reviewers.</p>
<p>Backward and forward citation searching was performed on all the included studies after the screening process using citationchaser<span class="citation" data-cites="Haddaway2022"><sup><a href="references.html#ref-Haddaway2022" role="doc-biblioref">18</a></sup></span> and the screen process was repeated until no further new studies were identified through citationchaser.</p>
</section>
<section id="data-charting-process-and-data-items" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="data-charting-process-and-data-items"><span class="header-section-number">3.2.3</span> Data Charting Process and Data Items</h3>
<p>Research questions were defined before the screening process and data was extracted based on the research questions in <a href="#nte-study1-research-q" class="quarto-xref">Note&nbsp;<span>3.1</span></a>.</p>
<div id="nte-study1-research-q" class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;3.1: Research Questions (Study 1)
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Is there an association between glycemic control and CVD risk?</li>
<li>Can CGM-derived metrics predict CVD risk?</li>
<li>What CGM-derived metrics are used in the literature?</li>
<li>Which cardiovascular markers and diseases are included as outcomes in the studies?</li>
<li>What characterizes study populations (age, sex, ethnicity, geographic location)?</li>
<li>What study designs are used (e.g., longitudinal cohort studies, randomized controlled trials, cross-sectional studies)?</li>
<li>How was data collected (e.g., clinical trial, epidemiological study, routinely collected data)?</li>
<li>What CGM devices were used?</li>
<li>What statistical models were used in the studies?</li>
<li>Is the data openly available?</li>
<li>Is the code openly available?</li>
</ol>
</div>
</div>
</section>
<section id="synthesis-of-results" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="synthesis-of-results"><span class="header-section-number">3.2.4</span> Synthesis of Results</h3>
<p>Study characteristics were synthesized using descriptive statistics and supplemented by a narrative summary. Only the most adjusted models in the main population for each study was considered in this review. This approach was necessary as several studies reported numerous estimates across varying adjustments, different combinations of CGM-derived metrics and CVD outcomes, and/or distinct subgroup stratifications. Given the large volume of literature, studies investigating clinical cardiovascular outcomes were prioritized in the main synthesis. While subclinical markers offer valuable insight into early vascular changes and disease progression, clinical outcomes are more directly relevant to cardiovascular risk prediction and clinical decision-making. The main synthesis of clinical outcomes included both effect estimates and measures of statistical significance whereas the supplementary synthesis on subclinical CVD focused primarily on creating an overview of the chosen CGM-derived metrics and the statistical significance of reported associations. All evaluation metrics mentioned in the studies doing prediction analyses were reported based on what the studies reported.</p>
</section>
</section>
<section id="study-populations" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="study-populations"><span class="header-section-number">3.3</span> Study Populations</h2>
<ul class="task-list">
<li><label><input type="checkbox">Signe, do you have ethical approval number or paper/protocol I can cite for the CANCAN study?</label></li>
</ul>
<p>Two datasets were used in this PhD project and are described in the following sections. Both studies were conducted in accordance with the principles of the Declaration of Helsinki and approved by the relevant institutional review boards. Written informed consent was obtained from all participants.<!-- [@Bergenstal2017] --></p>
<section id="cancan-data" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="cancan-data"><span class="header-section-number">3.3.1</span> CANCAN Data</h3>
<p>The CANCAN dataset was collected in an observational case-control study from three hospital outpatient clinics (Denmark). The aim of the CANCAN Study was to investigate if cardiac autonomic neuropathy (CAN) assessments, CGM and heart failure indicators could be used in risk stratification in people with T2D. Participants were included if they were adults (&gt; 18 years old) and had T2D for at least a year. Exclusion criteria were atrial fibrillation or laser-treated eye disease within the past three months, were pregnant or lactating, had a life-threatening disease (expected survival &lt; 1 year), or had cognitive disabilities rendering them unable to understand and give consent. Data were collected during a clinical examination, during which blood and urine samples were obtained, and a blinded CGM sensor was inserted. Blood samples to obtain NT-proBNP values were collected when the CGM sensors were returned, after the 2-week CGM data collection period had ended (<a href="#fig-cancan-timeline" class="quarto-xref">Figure&nbsp;<span>3.1</span></a>). In total, 159 participants were included since the rest were missing age, sex, HbA1c, BMI, NT-proBNP, HDL, total cholesterol, or eGFR and these values were needed for the analyses in Study II.</p>
<div id="fig-cancan-timeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cancan-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/cancan_timeline.png"><img src="figures/3_methods_fig/cancan_timeline.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cancan-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1: Data collection timeline for the CANCAN Study
</figcaption>
</figure>
</div>
</section>
<section id="t1d-exchange-data" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="t1d-exchange-data"><span class="header-section-number">3.3.2</span> T1D Exchange Data</h3>
<p>The publicly available T1D Exchange (T1DX) dataset, distributed by the Jaeb Center for Health Research under the protocol “Racial Differences in Mean CGM Glucose in Relation to HbA1c, was collected in 10 diabetes centers (US).<span class="citation" data-cites="JAEB_2016"><sup><a href="references.html#ref-JAEB_2016" role="doc-biblioref">19</a></sup></span> The data was collected to determine if there is a racial difference in the association between mean glucose and HbA1c between <a href="#acronyms_Black">non-Hispanic African Americans or Black (Black)</a> and <a href="#acronyms_White">non-Hispanic White (White)</a> people with T1D. In the T1DX study ethnicity and race was defined through self-identified and self-reported ethnicity/race verification forms where ethnicity was defined as Hispanic or Latino as: <em>“a person of Cuban, Mexican, Puerto Rican, South or Central American, or other Spanish culture or origin, regardless of race. The term “Spanish origin” could be used in addition to “Hispanic” or “Latino”“</em>.<span class="citation" data-cites="Bergenstal2017"><sup><a href="references.html#ref-Bergenstal2017" role="doc-biblioref">20</a>, suppl</sup></span> For race a participant defined as White was <em>“a person having origins in any of the original peoples of Europe, the Middle East or North Africa.”</em> and Black or African American people were defined as <em>“a person having origins in any of the Black racial groups of Africa. Terms such as “Haitian” or “Negro” can be used in addition to “Black” or “African American””</em>.<span class="citation" data-cites="Bergenstal2017"><sup><a href="references.html#ref-Bergenstal2017" role="doc-biblioref">20</a>, suppl</sup></span> In this thesis, the term race will be used moving forward, as it aligns with the terminology used by Bergenstal et al.<span class="citation" data-cites="Bergenstal2017"><sup><a href="references.html#ref-Bergenstal2017" role="doc-biblioref">20</a></sup></span>. However, I acknowledge that it is difficult to define race.<span class="citation" data-cites="Kaneshiro2011"><sup><a href="references.html#ref-Kaneshiro2011" role="doc-biblioref">21</a></sup></span> Of the 205 participants included in the study<span class="citation" data-cites="Bergenstal2017"><sup><a href="references.html#ref-Bergenstal2017" role="doc-biblioref">20</a></sup></span>, 101 were White and 104 were Black. For each race, two age groups were sampled 8 to &lt;18 years old and &gt;18. Each participant wore a blinded modified investigational version of Abbott Diabetes Care’s Flash Glucose Monitoring System (CGM) as continuously as possible for 12 weeks (<a href="#fig-t1dx-timeline" class="quarto-xref">Figure&nbsp;<span>3.2</span></a>). CGM data was sampled every 15 minutes in a range between 2.21 - 27.65 mmol/L (40 and 498 mg/dL). Blood samples were taken at enrollment, at some of the follow-up visits, and at the end of enrollment.</p>
<div id="fig-t1dx-timeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t1dx-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/3_methods_fig/t1dx_timeline.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t1dx-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.2: Data collection timeline for the T1DX Study
</figcaption>
</figure>
</div>
</section>
</section>
<section id="foundation-models-and-predictive-utility-of-cgm-data" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="foundation-models-and-predictive-utility-of-cgm-data"><span class="header-section-number">3.4</span> Foundation Models and Predictive Utility of CGM data</h2>
<p>The second study investigated whether a CGM foundation model could learn meaningful representations of CGM data and compared these learned representations with conventional CGM-derived metrics identified in Study I.<span class="citation" data-cites="Thomsen2026"><sup><a href="references.html#ref-Thomsen2026" role="doc-biblioref">3</a></sup></span></p>
<section id="data-and-participant-selection" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="data-and-participant-selection"><span class="header-section-number">3.4.1</span> Data and Participant Selection</h3>
<ul class="task-list">
<li><label><input type="checkbox">Check cancan data to find the range of the CGM censor in that study</label></li>
</ul>
<p>Both the CANCAN and the T1DX dataset was used for Study II. Participants with missing age, sex, HbA1c or BMI were excluded from both cohorts and in addition, CANCAN participants with missing NT-proBNP, HDL, total cholesterol, and <a href="#acronyms_eGFR">estimated glomerular filtration rate (eGFR)</a> they were also removed, since it was necessary to calculate the SCORE2-Diabetes risk score. T1DX participants with missing race data was also removed. Days with less than 70% of CGM data was removed as well as participants with less than one day of data from both datasets to ensure sufficient data for the analyses. Values exceeding the measurable range of the CGM devices were retained as the device’s upper and lower measurement limits. <em>For the CANCAN data, this range was (_____)</em> and for the T1DX data, the range was 2.21 - 27.65 mmol/L. <!-- The final number of participants included in Study II was 159 from the CANCAN dataset and 205 from the T1DX dataset. --></p>
</section>
<section id="transfer-learning-foundation-models-and-embeddings" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="transfer-learning-foundation-models-and-embeddings"><span class="header-section-number">3.4.2</span> Transfer Learning, Foundation Models and Embeddings</h3>
<p>Of the two CGM-specific foundation models based on self-supervised learning currently described in the literature (CGMformer by Lu et al., 2025<span class="citation" data-cites="YurunLu2025"><sup><a href="references.html#ref-YurunLu2025" role="doc-biblioref">22</a></sup></span> and GLUformer by Lutsker et al., 2026<span class="citation" data-cites="Lutsker2026"><sup><a href="references.html#ref-Lutsker2026" role="doc-biblioref">23</a></sup></span>), only the pretrained weights from the CGMformer by Lu et al.<span class="citation" data-cites="YurunLu2025"><sup><a href="references.html#ref-YurunLu2025" role="doc-biblioref">22</a></sup></span> were made publicly available, enabling reuse of the CGMformer model for downstream tasks. The CGMformer was therefore chosen and the data was organized in 24-hour long-format input to match the input requirements of the CGMformer. The output of the foundation model is learned representations of the input data, also known as embeddings and the head of the CGMformer were not available for retraining (<a href="#fig-cgmformer" class="quarto-xref">Figure&nbsp;<span>3.3</span></a>). By only having the backbone, the transfer learning strategy being used had to be replacing the head with a new, as shown in <a href="1-introduction.html#fig-tl" class="quarto-xref">Figure&nbsp;<span>1.2</span></a> as transfer three.</p>
<div id="fig-cgmformer" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cgmformer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/study2_cgmformer.png"><img src="figures/3_methods_fig/study_2_cgmformer.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cgmformer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.3: Illustration of how CGMformer is used in this analysis
</figcaption>
</figure>
</div>
<p>Embeddings are numerical vectors that summarizes the characteristics of the input glucose profile. A simple vector can be drawn as an arrow in a 2-dimensional space as shown in <a href="#fig-cancan-embedding" class="quarto-xref">Figure&nbsp;<span>3.4</span></a>, however the CGMformer gives a 128-dimensional embedding vector for each 24-hour CGM data input which is not easily visualized.</p>
<div id="fig-cancan-embedding" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cancan-embedding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/study2_embedding.png"><img src="figures/3_methods_fig/study2_embedding.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cancan-embedding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.4: Embeddings shown as 2-dimensional vectors with the angle <span class="math inline">\(\theta\)</span> between the two embeddings.
</figcaption>
</figure>
</div>
<p><a href="#acronyms_UMAP">Uniform Manifold Approximation and Projection (UMAP)</a> algorithm was used to reduce the dimensionality of the embeddings to two dimensions. The concept of dimensionality reduction is illustrated in <a href="#fig-dim_reduce" class="quarto-xref">Figure&nbsp;<span>3.5</span></a>. The <a href="#acronyms_UMAP">UMAP</a>s were visualized and compared with current literature, and later on used for prediction purposes.<span class="citation" data-cites="McInnes2018_umap YurunLu2025 Lutsker2026"><sup><a href="references.html#ref-YurunLu2025" role="doc-biblioref">22</a>–<a href="references.html#ref-McInnes2018_umap" role="doc-biblioref">24</a></sup></span>. The UMAPs were colored by TIR, and MAGE to investigate if the embeddings were able to capture relevant information about glycemic patterns. History of CVD and elevated NT-proBNP for the CANCAN embeddings were also used to color the UMAPs to investigate if the embeddings were able to capture relevant information about cardiovascular risk and race was used to color the T1DX embeddings to investigate if the embeddings were able to capture relevant information about racial differences in glycemic patterns.</p>
<div id="fig-dim_reduce" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-scap="Conceptual dimensionality reduction illustration">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dim_reduce-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/study_2_dim_reduce.png"><img src="figures/3_methods_fig/study_2_dim_reduce.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dim_reduce-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.5: Conceptual illustration of dimensionality reduction (read from left to right). Information from multiple dimensions can be represented using fewer dimensions while preserving information. This illustration does not show how UMAP works but instead is intended to convey the general concept of dimensionality reduction.
</figcaption>
</figure>
</div>
<p>Because embeddings are numerical vectors, they can be compared to quantify the similarity between glucose profiles, as demonstrated by Lutsker et al.<span class="citation" data-cites="Lutsker2026"><sup><a href="references.html#ref-Lutsker2026" role="doc-biblioref">23</a></sup></span> We therefore adopted a similar approach to assess the similarity between CGM-derived embeddings. Cosine similarity was used and it measures the angle between two embedding vectors independent of their magnitude (the length of the vectors). The cosine similarity is calculated by measuring the cosine angle between two vectors as shown by <span class="math inline">\(\theta\)</span> in <a href="#fig-cancan-embedding" class="quarto-xref">Figure&nbsp;<span>3.4</span></a>. The cosine similarity is a number between -1 and 1, where 1 means the two vectors are identical, 0 means they are unrelated, and -1 means that they are pointing in opposite directions(<a href="#fig-cancan-co_sim_emb" class="quarto-xref">Figure&nbsp;<span>3.6</span></a>). For the analyses in this study, cosine distance (1 − cosine similarity) was used because it expresses similarity as a distance measure, allowing embeddings with similar orientations to have small distances and facilitating downstream analyses and visualizations. The cosine distances range from 0 to 2 where 0 means the two vectors are pointing in the same direction, 1 means they are unrelated, and 2 means that they are pointing in opposite directions.</p>
<div id="fig-cancan-co_sim_emb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cancan-co_sim_emb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/study2_co_sim_emb.png"><img src="figures/3_methods_fig/study2_co_sim_emb.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cancan-co_sim_emb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.6: Embeddings shown with different cosine similarities. The cosine similarity is calculated as the cosine of the angle (<span class="math inline">\(\theta\)</span>) between two embeddings.
</figcaption>
</figure>
</div>
<p>Kernel density plots were used to visualize the distribution of cosine distances within specific clinical strata and across differing participants (<a href="#fig-cancan-clin_strata" class="quarto-xref">Figure&nbsp;<span>3.7</span></a>). Groupings were made based on days from the same participant (within-participant comparison), days from different participants with the same clinical strata (between-participant comparison), and days from different participants with different clinical strata(between-participant comparison) (<a href="#fig-cancan-clin_strata" class="quarto-xref">Figure&nbsp;<span>3.7</span></a>).</p>
<div id="fig-cancan-clin_strata" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-scap="Within and between participants comparison">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cancan-clin_strata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/study2_clin_strata.png"><img src="figures/3_methods_fig/study2_clin_strata.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cancan-clin_strata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.7: The sex strata is used as an example to illustrate the cosine distance analysis of the within and between cosine distance pairs
</figcaption>
</figure>
</div>
<p>The main focus for the participant comparisons were TIR and HbA1c. The thresholds were as followed: TIR ≥ 70% (70–180 mg/dL, 3.9–10.0 mmol/L) and HbA1c &lt;7.0 % (&lt; 53 mmol/mol).<span class="citation" data-cites="Danne2017"><sup><a href="references.html#ref-ADA2026_ch7" role="doc-biblioref">26</a></sup></span> Additional UMAP visualizations were generated by coloring participants according to race, MAGE (&lt; 70 mg/dL ( &lt; 3.9 mmol/L )),<span class="citation" data-cites="Danne2017"><sup><a href="references.html#ref-Danne2017" role="doc-biblioref">25</a></sup></span> and NT-proBNP (NT-proBNP ≤ 125 pg/mL).<span class="citation" data-cites="Heidenreich2022"><sup><a href="references.html#ref-Welsh2022" role="doc-biblioref">28</a></sup></span> These categorizations were used solely to facilitate interpretation of the UMAP visualizations and were not incorporated into model development or any statistical analyses. Participants with missing values for a given characteristic were excluded only from the corresponding visualization and remained eligible for all subsequent analyses.</p>
</section>
</section>
<section id="cardiovascular-risk-assessment" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="cardiovascular-risk-assessment"><span class="header-section-number">3.5</span> Cardiovascular Risk Assessment</h2>
<p>The following section is about cardiovascular risk assessment evaluated predicting NT-proBNP as a binary outcome using a &gt;125 pg/mL threshold.<span class="citation" data-cites="mcdonagh2021 Heidenreich2022 Welsh2022"><sup><a href="references.html#ref-Heidenreich2022" role="doc-biblioref">27</a>–<a href="references.html#ref-mcdonagh2021" role="doc-biblioref">29</a></sup></span> Only the cross-sectional CANCAN dataset was used for the cardiovascular risk assessment. The focus was to test the predictive power of CGM data both as represented as embeddings and as well-established CGM-derived metrics. Some models also included clinical predictors to compare up against baseline models. Prediction models integrated clinical, standard CGM-derived, and learned representations.</p>
<section id="predictors" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="predictors"><span class="header-section-number">3.5.1</span> Predictors</h3>
<p>Inspiration was drawn from the SCORE2-Diabetes risk score, which is a 10-year CVD risk score for european people with diabetes. It was decided to use the input predictors of the SCORE2-Diabetes risk score as the clinical set of predictors used in this study.<span class="citation" data-cites="Pennells2023_score2dm"><sup><a href="references.html#ref-Pennells2023_score2dm" role="doc-biblioref">30</a></sup></span> This resulted in set of clinical predictors including age, sex, smoking status, systolic blood pressure, total cholesterol, and HbA1c.<span class="citation" data-cites="Pennells2023_score2dm"><sup><a href="references.html#ref-Pennells2023_score2dm" role="doc-biblioref">30</a></sup></span> Initial testing showed that the numbers of predictors had to be limited due to the small sample size and the SCORE2-Diabetes risk score was chosen as another way to represent the clinical predictor set while keeping the number of predictors down. Additionally age was tested as a predictor on its own to see if it was a strong predictor of elevated NT-proBNP, since NT-proBNP is known to increase with age.<span class="citation" data-cites="NICE_2028_guidelines"><sup><a href="references.html#ref-NICE_2028_guidelines" role="doc-biblioref">31</a></sup></span> Time in range (TIR) and mean amplitude of glycemic excursions (MAGE) were chosen as they were the CGM-derived metrics most commonly used in the literature based on the findings from Study I.<span class="citation" data-cites="Thomsen2026"><sup><a href="references.html#ref-Thomsen2026" role="doc-biblioref">3</a></sup></span> All CGM-derived metrics in this thesis were calculated using the <a href="#acronyms_IGLU">Interpreting Glucose Data from Continuous Glucose Monitors (IGLU)</a> package<span class="citation" data-cites="iglu_package iglu_package_paper"><sup><a href="references.html#ref-iglu_package" role="doc-biblioref">32</a>,<a href="references.html#ref-iglu_package_paper" role="doc-biblioref">33</a></sup></span> in R (default settings). TIR was calculated as the percentage of time spent in the range of 3.9–10.0 mmol/L (70–180 mg/dL).<span class="citation" data-cites="Danne2017"><sup><a href="references.html#ref-Danne2017" role="doc-biblioref">25</a></sup></span> MAGE was calculated as the mean amplitude of glucose excursions, where the included excursions were consecutive peak-to-nadir (or nadir-to-peak) glucose differences exceeding one standard deviation of the individual’s glucose measurementsDoes . The <a href="#acronyms_IGLU">IGLU</a> implementation computationally reproduces the original manual procedure proposed by Service et al.<span class="citation" data-cites="Service1970"><sup><a href="references.html#ref-Service1970" role="doc-biblioref">34</a></sup></span> The CGMformer generated one 128-dimensional embedding for each 24-hour CGM recording. Because NT-proBNP was measured at the participant level, a single embedding was required for each participant. Therefore, embeddings from multiple recording days were aggregated using pooling to obtain one participant-level embedding. Both minimum, maximum, and mean pooling were explored to determine the most effective aggregation method. Maximum pooling was considered the default based on previous work.<span class="citation" data-cites="Lutsker2026"><sup><a href="references.html#ref-Lutsker2026" role="doc-biblioref">23</a></sup></span> The resulting 128-dimensional embeddings were subsequently reduced to two dimensions using UMAP, thereby enabling their use in the prediction models while keeping the number of predictors down to a minimum.</p>
</section>
<section id="model-development-and-evaluation" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="model-development-and-evaluation"><span class="header-section-number">3.5.2</span> Model Development and Evaluation</h3>
<p>Prediction models were developed using logistic regression to predict elevated NT-proBNP (&gt;125 pg/mL) as a binary outcome. The models were evaluated using the area under the receiver operating characteristic curve (AUROC) as the primary metric. Bootstrap with optimism correction was employed for internal validation because of the limited sample size and the absence of an external validation cohort.<span class="citation" data-cites="Collins2024 Wahl2016 Riley2023"><sup><a href="references.html#ref-Collins2024" role="doc-biblioref">35</a>–<a href="references.html#ref-Riley2023" role="doc-biblioref">37</a></sup></span> The method repeatedly sampled bootstrap samples by sampling with replacement from the original dataset. For each bootstrap sample, the prediction model is fitted and its performance is evaluated both in the bootstrap sample (apparent performance) and in the original dataset (test performance). The difference between these two performance estimates represents the optimism due to overfitting. Averaging the optimism across all bootstrap samples and subtracting it from the apparent performance of the model fitted to the full dataset yields an optimism-corrected estimate of model performance. Internal validation was performed using 500 bootstrap resamples.<span class="citation" data-cites="Collins2024 Riley2023"><sup><a href="references.html#ref-Collins2024" role="doc-biblioref">35</a>,<a href="references.html#ref-Riley2023" role="doc-biblioref">37</a></sup></span> Prediction stability plots were reported for each model to evaluate the stability of predictions produced by a specific model strategy when the training data changes.<span class="citation" data-cites="Riley2023"><sup><a href="references.html#ref-Riley2023" role="doc-biblioref">37</a></sup></span> <!-- Risk distribution plots were reported for each model across all bootstrap samples.[@VanCalster2025; @Riley2023] --></p>
</section>
<section id="prediction-scheme-overview" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="prediction-scheme-overview"><span class="header-section-number">3.5.3</span> Prediction Scheme Overview</h3>
<p>The prediction models were structured hierarchically based on clinical variables (Model A) and the calculated SCORE2-Diabetes score (Model B) in the configurations shown in <a href="#tbl-models" class="quarto-xref">Table&nbsp;<span>3.3</span></a></p>
<div id="tbl-models" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.3: Overview of models and predictors
</figcaption>
<div aria-describedby="tbl-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Model family</th>
<th style="text-align: center;">Model</th>
<th style="text-align: left;">Baseline predictors</th>
<th style="text-align: left;">Additional predictors</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Clinical</td>
<td style="text-align: center;"><strong>A0</strong></td>
<td style="text-align: left;">Age</td>
<td style="text-align: left;">–</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clinical</td>
<td style="text-align: center;"><strong>A1</strong></td>
<td style="text-align: left;">Clinical variables*</td>
<td style="text-align: left;">–</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Clinical</td>
<td style="text-align: center;"><strong>A2</strong></td>
<td style="text-align: left;">Clinical variables*</td>
<td style="text-align: left;">TIR + MAGE</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clinical</td>
<td style="text-align: center;"><strong>A3</strong></td>
<td style="text-align: left;">Clinical variables*</td>
<td style="text-align: left;">UMAP dimensions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCORE2-Diabetes</td>
<td style="text-align: center;"><strong>B1</strong></td>
<td style="text-align: left;">SCORE2-Diabetes score</td>
<td style="text-align: left;">–</td>
</tr>
<tr class="even">
<td style="text-align: left;">SCORE2-Diabetes</td>
<td style="text-align: center;"><strong>B2</strong></td>
<td style="text-align: left;">SCORE2-Diabetes score</td>
<td style="text-align: left;">TIR + MAGE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCORE2-Diabetes</td>
<td style="text-align: center;"><strong>B3</strong></td>
<td style="text-align: left;">SCORE2-Diabetes score</td>
<td style="text-align: left;">UMAP dimensions</td>
</tr>
<tr class="even">
<td style="text-align: left;">CGM only</td>
<td style="text-align: center;"><strong>C1</strong></td>
<td style="text-align: left;">TIR + MAGE</td>
<td style="text-align: left;">–</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Embeddings only</td>
<td style="text-align: center;"><strong>D1</strong></td>
<td style="text-align: left;">UMAP dimensions</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<div style="font-size: 0.85em; margin-top: -10px;">
<p><sup>*</sup><em>Clinical variables are the same as those included in the SCORE2-Diabetes risk model: Age, sex, smoking status, systolic blood pressure, HDL cholesterol, total cholesterol, diabetes duration, HbA1c, and eGFR.<span class="citation" data-cites="Pennells2023_score2dm"><sup><a href="references.html#ref-Pennells2023_score2dm" role="doc-biblioref">30</a></sup></span></em><br>
<em>TIR = Time in Range; MAGE = Mean Amplitude of Glycemic Excursions.</em></p>
</div>
</div>
</figure>
</div>
<!-- ****************************************************************************************** -->
</section>
</section>
<section id="algorithmic-fairness-and-blood-glucose-prediction" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="algorithmic-fairness-and-blood-glucose-prediction"><span class="header-section-number">3.6</span> Algorithmic Fairness and Blood Glucose Prediction</h2>
<p>The third study was investigating racial bias in a data driven machine learning model only based on blood glucose measurements from a CGM device.</p>
<section id="preprocessing-of-cgm-data-for-forecasting" class="level3" data-number="3.6.1">
<h3 data-number="3.6.1" class="anchored" data-anchor-id="preprocessing-of-cgm-data-for-forecasting"><span class="header-section-number">3.6.1</span> Preprocessing of CGM data for Forecasting</h3>
<p>A prediction horizon of 60 minutes was chosen because it provides sufficient time for preventive interventions for hypoglycemia and hyperglycemia, such as insulin dose adjustments or carbohydrate intake, while accounting for the 15-minute sampling interval of the CGM device and the physiological delay between blood and interstitial glucose measurements.<span class="citation" data-cites="ADA2026_ch7"><sup><a href="references.html#ref-ADA2026_ch7" role="doc-biblioref">26</a></sup></span></p>
<p>Accordingly, the CGM data were divided into consecutive 60-minute windows containing four glucose measurements to predict glucose levels 60 minutes into the future, as illustrated in <a href="#fig-study3_pred_horizon" class="quarto-xref">Figure&nbsp;<span>3.8</span></a>. Prediction windows containing missing CGM values were excluded.</p>
<div id="fig-study3_pred_horizon" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-scap="The creation of samples in study III">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-study3_pred_horizon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/study3_pred_horizon.png"><img src="figures/3_methods_fig/study3_pred_horizon.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-study3_pred_horizon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.8: The prediction horizon and overview of the creation of samples (predictors and outcomes).
</figcaption>
</figure>
</div>
</section>
<section id="partitioning-of-the-dataset" class="level3" data-number="3.6.2">
<h3 data-number="3.6.2" class="anchored" data-anchor-id="partitioning-of-the-dataset"><span class="header-section-number">3.6.2</span> Partitioning of the Dataset</h3>
<p>The T1DX dataset was randomly resampled without replacement at the participant level to avoid data leakage and to evaluate model performance on independent participants. As illustrated in <a href="#fig-study3_partitioning" class="quarto-xref">Figure&nbsp;<span>3.9</span></a>, training subsets with varying proportions of Black and White participants were generated by randomly selecting participants from the original dataset while keeping the train-test split at the participant level. Eleven training set compositions were created, ranging from 100% White/0% Black to 0% White/100% Black in 10% increments.</p>
<p>Because some training subsets consisted entirely of participants from a single racial group, the maximum training set size on participant level was constrained by the size of the smaller racial group minus the participants kept for testing. Consequently, each training subset contained approximately half the number of participants in the original T1DX dataset. Repeating this procedure for each participant resulted in 2,255 training datasets (205 participants × 11 training set compositions) and 205 independent test sets. Throughout all resampling procedures, all CGM recordings from a participant were kept together to prevent data leakage between the training and test sets.</p>
<div id="fig-study3_partitioning" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-study3_partitioning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/study3_partitioning.png"><img src="figures/3_methods_fig/study3_partitioning.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-study3_partitioning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.9: The prediction horizon and overview of the creation of subsets for training.
</figcaption>
</figure>
</div>
<p>Eleven subsets were created for each of the participants and the last week’s data was chosen to test on as illustrated in <a href="#fig-study3_train_finetune_test_split" class="quarto-xref">Figure&nbsp;<span>3.10</span></a> To preserve sample size, one week was chosen because participants had varying amount of CGM data and the participant with the least amount of data had ~ 2 weeks. The remaining data was used for training the models.</p>
<div id="fig-study3_train_finetune_test_split" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-scap="Creating training and test sets">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-study3_train_finetune_test_split-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/study3_train_finetune_test_split.png"><img src="figures/3_methods_fig/study3_train_finetune_test_split.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-study3_train_finetune_test_split-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.10: The splitting of a participants data to create training and test sets
</figcaption>
</figure>
</div>
</section>
<section id="model-selection-and-training-approaches" class="level3" data-number="3.6.3">
<h3 data-number="3.6.3" class="anchored" data-anchor-id="model-selection-and-training-approaches"><span class="header-section-number">3.6.3</span> Model Selection and Training Approaches</h3>
<p>A <a href="#acronyms_LSTM">long short term memory model (LSTM)</a> network architecture based on van Doorn et al.<span class="citation" data-cites="vanDoorn2021"><sup><a href="references.html#ref-vanDoorn2021" role="doc-biblioref">38</a></sup></span> was used (two LSTM layers followed by a dense layer). All the training data was scaled to be within the range of zero to one. Hyperparameters were optimized once prior to the repeated model development using grid search and data from all participants except the last week. The gridsearch included the number of neurons in the LSTM layers, activation function, dropout rate, batch size, learning rate, learning rate decay, and early stopping patience. The selected hyperparameter configuration was subsequently fixed and applied to all <a href="#acronyms_LSTM">LSTM</a> models The complete hyperparameter tuning procedure and implementation are available in the accompanying GitHub repository.<span class="citation" data-cites="Thomsen_github_1"><sup><a href="references.html#ref-Thomsen_github_1" role="doc-biblioref">39</a></sup></span></p>
<p>Four training approaches were used when the models for each participant were developed as described below and illustrated in <a href="#fig-study3_training_approaches" class="quarto-xref">Figure&nbsp;<span>3.11</span></a>. Three <a href="#acronyms_LSTM">LSTM</a> models and the <a href="#acronyms_LOCF">last observation carried forward (LOCF)</a> as a naive baseline. 1. <strong><a href="#acronyms_LOCF">LOCF</a>:</strong> In the LOCF model, a given CGM measurement (x4) was used to predict blood glucose values 60 minutes in advance (x8) in the test set by assuming no change in the last 60 minutes. 2. <strong>Base-Individual:</strong> In the Base-Individual model, each participant’s complete CGM data (except for the last week, which was used for the testing data) was used for training. 3. <strong>Base-Generalized:</strong> Here, for each participant, the 11 training corresponding datasets described above were used to generate 11 separate models, which were all subsequently tested on the given participant’s last week of CGM data. 4. <strong>Transfer Learned:</strong> This model mirrored the Base-Generalized Model’s setup. However, the 11 trained models for each participant were subsequently tailored to the given participant’s complete CGM data (except for the last week, which was used for the testing data). The transfer learning technique used is described as transfer 2 in <a href="1-introduction.html#fig-tl" class="quarto-xref">Figure&nbsp;<span>1.2</span></a>.</p>
<div id="fig-study3_training_approaches" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-scap="The four training approaches in study III">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-study3_training_approaches-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/study3_training_approaches.png"><img src="figures/3_methods_fig/study3_training_approaches.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-study3_training_approaches-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.11: The four training approaches. The Base-Individual, Base-Generalized, and Transfer Learned models were based on an LSTM architecture. The base layer (green) consisted of two LSTM layers, while the task-specific layer (blue) consisted of a single dense layer.
</figcaption>
</figure>
</div>
</section>
<section id="model-evaluation" class="level3" data-number="3.6.4">
<h3 data-number="3.6.4" class="anchored" data-anchor-id="model-evaluation"><span class="header-section-number">3.6.4</span> Model Evaluation</h3>
<p>To evaluate model performance, each participant’s last week’s data (672 measurements) was reserved for internal testing (<a href="#fig-study3_train_finetune_test_split" class="quarto-xref">Figure&nbsp;<span>3.10</span></a>). Model accuracy was assessed by calculating the root mean squared error (RMSE) for each participant across all four modeling approaches. For the LOCF and Base-Individual models, this yielded one RMSE value for each of the 101 White participants and 104 Black participants. For the Base-Generalized and Transfer Learned models, RMSEs were calculated for each participant across 11 data subsets, each representing a unique proportion of White and Black participants. Performance was summarized as the mean RMSE with corresponding 95% confidence intervals (CIs) for each racial group. To evaluate the predictive performance across different training subset compositions for the Base-Generalized and Transfer Learned models, an <a href="#acronyms_LMEM">LMEM</a> was fitted because each participant contributed multiple RMSE values from training subsets with varying proportions of White and Black participants. Participant-specific random intercepts were included to account for the repeated-measures structure. Fixed effects included the proportion of White participants in the training data, participant race, age, sex, training data sample size, and their interaction terms. It was further assumed that the varying proportions of Black and White participants in the training data subsets would affect the performance and an interaction term was therefore added. The interaction term allowed for different slopes in the LMEM which allowed us to test the hypothesis. It was hypothesized that when plotting the proportion of White participants in the training data against the RMSE, the slope would be negative for White participants and positive for Black participants (<a href="#fig-study3_rmse" class="quarto-xref">Figure&nbsp;<span>3.12</span></a>). This would indicate that as the proportion of White participants in the training data increased, the RMSE decreased for White participants and increased for Black participants, indicating racial bias in the model. The Base-Individual model would perform the worst since it was trained on the least amount of data and the Transfer Learned model would remove the slopes that were expected to be seen in the Base-Generalized models.</p>
<div id="fig-study3_rmse" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-study3_rmse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/study3_rmse.png"><img src="figures/3_methods_fig/study3_rmse.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-study3_rmse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.12: The hypothesis for the results of the linear mixed effect models.
</figcaption>
</figure>
</div>
<p>Surveillance error grids (SEG) were used to get a general idea of the clinical risk of the prediction models.<span class="citation" data-cites="Tian2024"><sup><a href="references.html#ref-Tian2024" role="doc-biblioref">40</a></sup></span> The error grids are originally developed for the regulatory bodies to asses clinical accuracy of blood glucose monitoring in post-surveillance before the wide spread use of CGM devices.<span class="citation" data-cites="Tian2024"><sup><a href="references.html#ref-Klonoff2014" role="doc-biblioref">41</a></sup></span> and the results should therefore be interpreted with caution when using CGM data. The SEG is a 600x600 grid assigned an individual risk score to each datapoint with 15 colored zones, each indicating severity of a monitoring error that is acted upon in regards to risk of hypoglycemia or hyperglycemia (<a href="#fig-study3_SEG" class="quarto-xref">Figure&nbsp;<span>3.13</span></a>).<span class="citation" data-cites="Klonoff2014"><sup><a href="references.html#ref-Klonoff2014" role="doc-biblioref">41</a></sup></span> To facilitate interpretation, the 15 surveillance error grid zones were collapsed into the five broader risk zones (“No”, “Slight”, “Moderate”, “High”, and “Extreme”), as previously suggested in the literature.<span class="citation" data-cites="Tian2024"><sup><a href="references.html#ref-Tian2024" role="doc-biblioref">40</a></sup></span> Predictions outside of 0–33 mmol/L were changed to 0 or 33 mmol/L to keep within the upper and lower bounds of the surveillance error grid.</p>
<div id="fig-study3_SEG" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-scap="surveillance error grid">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-study3_SEG-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><a href="https://raw.githubusercontent.com/HeleneThomsen/dissertation/main/figures/3_methods_fig/study3_SEG_empty.png"><img src="figures/3_methods_fig/study3_SEG_empty.png" class="img-fluid figure-img"></a></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-study3_SEG-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.13: Surveillance error grid showing the clinical risk associated with prediction errors. The green region indicates no clinical risk, whereas yellow, orange, and red regions represent increasing levels of clinical risk.
</figcaption>
</figure>
</div>


<div id="refs" class="references csl-bib-body" role="list" style="display: none">
<div id="ref-Tricco2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Tricco AC, Lillie E, Zarin W, et al. PRISMA extension for scoping reviews (PRISMA-ScR): Checklist and explanation. Annals of internal medicine 2018;169(7):467–7. </div>
</div>
<div id="ref-Peters2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Peters MDJ, Godfrey C, McInerney P, Munn Z, Tricco AC, Khalil H. Chapter 10: Scoping reviews [Internet]. In: Aromataris E, Lockwood C, Porritt K, Pilla B, Jordan Z, editors. JBI manual for evidence synthesis. JBI; 2024. Available from: <a href="https://jbi-global-wiki.refined.site/space/MANUAL/355862497/10.+Scoping+reviews">https://jbi-global-wiki.refined.site/space/MANUAL/355862497/10.+Scoping+reviews</a></div>
</div>
<div id="ref-Thomsen2026" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Thomsen HB, Lebiecka-Johansen B, Nørgaard O, et al. Continuous glucose monitoring–derived metrics and cardiovascular risk among people with diabetes: Systematic scoping review. JMIR Diabetes [Internet] 2026;11:e89374. Available from: <a href="https://doi.org/10.2196/89374">https://doi.org/10.2196/89374</a></div>
</div>
<div id="ref-Foreman2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Foreman YD, Doorn WPTM van, Schaper NC, et al. Greater daily glucose variability and lower time in range assessed with continuous glucose monitoring are associated with greater aortic stiffness: The maastricht study. Diabetologia 2021;64(8):1880–92. </div>
</div>
<div id="ref-Yapanis2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Yapanis M, James S, Craig ME, O’Neal D, Ekinci EI. Complications of diabetes and metrics of glycemic management derived from continuous glucose monitoring. The journal of clinical endocrinology and metabolism 2022;107(6):e2221–36. </div>
</div>
<div id="ref-Helleputte2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Helleputte S, Calders P, Rodenbach A, et al. Time-varying parameters of glycemic control and glycation in relation to arterial stiffness in patients with type 1 diabetes. Cardiovascular diabetology 2022;21(1):277–10. </div>
</div>
<div id="ref-Lu2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Lu J, Wang C, Shen Y, et al. Time in range in relation to all-cause and cardiovascular mortality in patients with type 2 diabetes: A prospective cohort study. Diabetes care 2021;44(2):549–55. </div>
</div>
<div id="ref-Martinez2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Martinez M, Santamarina J, Pavesi A, Musso C, Umpierrez GE. Glycemic variability and cardiovascular disease in patients with type 2 diabetes. BMJ open diabetes research &amp; care 2021;9(1):e002032–. </div>
</div>
<div id="ref-Mita2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Mita T, Katakami N, Okada Y, et al. Continuous glucose monitoring-derived time in range and CV are associated with altered tissue characteristics of the carotid artery wall in people with type 2 diabetes. Diabetologia 2023;66(12):2356–67. </div>
</div>
<div id="ref-Lu2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">Lu J, Ma X, Shen Y, et al. Time in range is associated with carotid intima-media thickness in type 2 diabetes. Diabetes technology &amp; therapeutics 2020;22(2):72–8. </div>
</div>
<div id="ref-Mo2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">Mo Y, Zhou J, Li M, et al. Glycemic variability is associated with subclinical atherosclerosis in chinese type 2 diabetic patients. Cardiovascular diabetology 2013;12(1):15–5. </div>
</div>
<div id="ref-Wakasugi2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">Wakasugi S, Mita T, Katakami N, et al. Associations between continuous glucose monitoring-derived metrics and arterial stiffness in japanese patients with type 2 diabetes. Cardiovascular diabetology 2021;20(1):15–2. </div>
</div>
<div id="ref-Magri2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Magri CJ, Mintoff D, Camilleri L, Xuereb RG, Galea J, Fava S. Relationship of hyperglycaemia, hypoglycaemia, and glucose variability to atherosclerotic disease in type 2 diabetes. Journal of Diabetes Research [Internet] 2018;2018(1):7464320. Available from: <a href="https://onlinelibrary.wiley.com/doi/abs/10.1155/2018/7464320">https://onlinelibrary.wiley.com/doi/abs/10.1155/2018/7464320</a></div>
</div>
<div id="ref-Su2011" class="csl-entry" role="listitem">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">Su G, Mi S, Tao H, et al. Association of glycemic variability and the presence and severity of coronary artery disease in patients with type 2 diabetes. Cardiovascular diabetology 2011;10(1):19–9. </div>
</div>
<div id="ref-Tang2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">15. </div><div class="csl-right-inline">Tang X, Li S, Wang Y, et al. Glycemic variability evaluated by continuous glucose monitoring system is associated with the 10-y cardiovascular risk of diabetic patients with well-controlled HbA1c. Clinica chimica acta 2016;461:146–50. </div>
</div>
<div id="ref-Zhang2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">16. </div><div class="csl-right-inline">Zhang X, Xu X, Jiao X, et al. The effects of glucose fluctuation on the severity of coronary artery disease in type 2 diabetes mellitus. Journal of diabetes research 2013;2013(2013):1–6. </div>
</div>
<div id="ref-Thomas2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">17. </div><div class="csl-right-inline">Thomas J, Graziosi S, Brunton J, et al. <span>EPPI-Reviewer</span>: Advanced software for systematic reviews, maps and evidence synthesis [Internet]. University College London; EPPI Centre, UCL Social Research Institute; 2023. Available from: <a href="https://eppi.ioe.ac.uk/cms/er4/">https://eppi.ioe.ac.uk/cms/er4/</a></div>
</div>
<div id="ref-Haddaway2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">18. </div><div class="csl-right-inline">Haddaway NR, Grainger M, Gray CT. Citationchaser: A tool for transparent and efficient forward and backward citation chasing in systematic searching. Research synthesis methods 2022;13(4):533–45. </div>
</div>
<div id="ref-JAEB_2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">19. </div><div class="csl-right-inline">Jaeb Center for Health Research. Jaeb center for health research: Datasets &amp; documents [Internet]. 2016 [cited 2024 Feb 20];Available from: <a href="https://public.jaeb.org/datasets/diabetes">https://public.jaeb.org/datasets/diabetes</a></div>
</div>
<div id="ref-Bergenstal2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">20. </div><div class="csl-right-inline">Bergenstal RM, Gal RL, Connor CG, et al. Racial differences in the relationship of glucose concentrations and hemoglobin A1c levels. Annals of Internal Medicine 2017;167(2):95–102. </div>
</div>
<div id="ref-Kaneshiro2011" class="csl-entry" role="listitem">
<div class="csl-left-margin">21. </div><div class="csl-right-inline">Kaneshiro B, Geling O, Gellert K, Millar L. The challenges of collecting data on race and ethnicity in a diverse, multiethnic state. Hawaii medical journal (1962) 2011;70(8):168–71. </div>
</div>
<div id="ref-YurunLu2025" class="csl-entry" role="listitem">
<div class="csl-left-margin">22. </div><div class="csl-right-inline">Lu Y, Liu D, Liang Z, et al. A pretrained transformer model for decoding individual glucose dynamics from continuous glucose monitoring data. National science review 2025;12(5):nwaf039–. </div>
</div>
<div id="ref-Lutsker2026" class="csl-entry" role="listitem">
<div class="csl-left-margin">23. </div><div class="csl-right-inline">Lutsker G, Sapir G, Shilo S, et al. A foundation model for continuous glucose monitoring data. Nature (London) 2026;650(8103):978–86. </div>
</div>
<div id="ref-McInnes2018_umap" class="csl-entry" role="listitem">
<div class="csl-left-margin">24. </div><div class="csl-right-inline">McInnes L, Healy J, Melville J. UMAP: Uniform manifold approximation and projection for dimension reduction. arXiv preprint arXiv:180203426 [Internet] 2018;Available from: <a href="https://arxiv.org/abs/1802.03426">https://arxiv.org/abs/1802.03426</a></div>
</div>
<div id="ref-Danne2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">25. </div><div class="csl-right-inline">Danne T, Nimri R, Battelino T, et al. International consensus on use of continuous glucose monitoring. Diabetes care 2017;40(12):1631–40. </div>
</div>
<div id="ref-ADA2026_ch7" class="csl-entry" role="listitem">
<div class="csl-left-margin">26. </div><div class="csl-right-inline">American Diabetes Association Professional Practice Committee for Diabetes*. 7. <span>Diabetes</span> <span>Technology</span>: <span>Standards</span> of <span>Care</span> in <span>Diabetes</span>—2026. Diabetes Care [Internet] 2026 [cited 2026 July 13];49(Supplement_1):S150–65. Available from: <a href="https://doi.org/10.2337/dc26-S007">https://doi.org/10.2337/dc26-S007</a></div>
</div>
<div id="ref-Heidenreich2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">27. </div><div class="csl-right-inline">Heidenreich PA, Bozkurt B, Aguilar D, et al. 2022 AHA/ACC/HFSA guideline for the management of heart failure: A report of the american college of cardiology/american heart association joint committee on clinical practice guidelines. Journal of the American College of Cardiology [Internet] 2022;79(17):e263–421. Available from: <a href="https://www.sciencedirect.com/science/article/pii/S0735109721083959">https://www.sciencedirect.com/science/article/pii/S0735109721083959</a></div>
</div>
<div id="ref-Welsh2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">28. </div><div class="csl-right-inline">Welsh P, Campbell RT, Mooney L, et al. Reference ranges for NT-proBNP (n-terminal pro-b-type natriuretic peptide) and risk factors for higher NT-proBNP concentrations in a large general population cohort. Circulation: Heart Failure [Internet] 2022;15(10):e009427. Available from: <a href="https://www.ahajournals.org/doi/abs/10.1161/CIRCHEARTFAILURE.121.009427">https://www.ahajournals.org/doi/abs/10.1161/CIRCHEARTFAILURE.121.009427</a></div>
</div>
<div id="ref-mcdonagh2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">29. </div><div class="csl-right-inline">McDonagh TA, Metra M, Adamo M, et al. 2021 <span>ESC</span> <span>Guidelines</span> for the diagnosis and treatment of acute and chronic heart failure: <span>Developed</span> by the <span>Task</span> <span>Force</span> for the diagnosis and treatment of acute and chronic heart failure of the <span>European</span> <span>Society</span> of <span>Cardiology</span> (<span>ESC</span>) <span>With</span> the special contribution of the <span>Heart</span> <span>Failure</span> <span>Association</span> (<span>HFA</span>) of the <span>ESC</span>. European Heart Journal [Internet] 2021 [cited 2026 July 13];42(36):3599–726. Available from: <a href="https://doi.org/10.1093/eurheartj/ehab368">https://doi.org/10.1093/eurheartj/ehab368</a></div>
</div>
<div id="ref-Pennells2023_score2dm" class="csl-entry" role="listitem">
<div class="csl-left-margin">30. </div><div class="csl-right-inline">Pennells L, Kaptoge S, Østergaard HB, et al. SCORE2-diabetes: 10-year cardiovascular risk estimation in type 2 diabetes in europe. European heart journal 2023;44(28):2544–56. </div>
</div>
<div id="ref-NICE_2028_guidelines" class="csl-entry" role="listitem">
<div class="csl-left-margin">31. </div><div class="csl-right-inline">National Guideline Centre (UK). Chronic heart failure in adults: Diagnosis and management [Internet]. London, UK: National Institute for Health; Care Excellence (NICE); 2018. Available from: <a href="https://www.ncbi.nlm.nih.gov/books/NBK536098/">https://www.ncbi.nlm.nih.gov/books/NBK536098/</a></div>
</div>
<div id="ref-iglu_package" class="csl-entry" role="listitem">
<div class="csl-left-margin">32. </div><div class="csl-right-inline">Chun E, Broll S, Buchanan D, et al. <span class="nocase">iglu:</span> Interpreting glucose data from continuous glucose monitors. 2023. </div>
</div>
<div id="ref-iglu_package_paper" class="csl-entry" role="listitem">
<div class="csl-left-margin">33. </div><div class="csl-right-inline">Broll S, Urbanek J, Buchanan D, et al. <a href="https://doi.org/10.1371/journal.pone.0248560">Interpreting blood glucose data with <span>R</span> package <span class="nocase">iglu</span></a>. PloS One 2021;16(4):e0248560. </div>
</div>
<div id="ref-Service1970" class="csl-entry" role="listitem">
<div class="csl-left-margin">34. </div><div class="csl-right-inline">Service FJ, Molnar GD, Rosevear JW, Ackerman E, Gatewood LC, Taylor WF. Mean amplitude of glycemic excursions, a measure of diabetic instability. Diabetes (New York, NY) 1970;19(9):644–55. </div>
</div>
<div id="ref-Collins2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">35. </div><div class="csl-right-inline">Collins GS, Moons KGM, Dhiman P, et al. TRIPOD+AI statement: Updated guidance for reporting clinical prediction models that use regression or machine learning methods. BMJ [Internet] 2024;385. Available from: <a href="https://www.bmj.com/content/385/bmj-2023-078378">https://www.bmj.com/content/385/bmj-2023-078378</a></div>
</div>
<div id="ref-Wahl2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">36. </div><div class="csl-right-inline">Wahl S, Boulesteix A-L, Zierer A, Thorand B, Wiel MA van de. Assessment of predictive performance in incomplete data by combining internal validation and multiple imputation. BMC Medical Research Methodology [Internet] 2016 [cited 2026 Feb 11];16(1):144. Available from: <a href="https://doi.org/10.1186/s12874-016-0239-7">https://doi.org/10.1186/s12874-016-0239-7</a></div>
</div>
<div id="ref-Riley2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">37. </div><div class="csl-right-inline">Riley RD, Pate A, Dhiman P, Archer L, Martin GP, Collins GS. Clinical prediction models and the multiverse of madness. BMC medicine 2023;21(1):502–9. </div>
</div>
<div id="ref-vanDoorn2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">38. </div><div class="csl-right-inline">Doorn WPTM van, Foreman YD, Schaper NC, et al. Machine learning-based glucose prediction with use of continuous glucose and physical activity monitoring data: The maastricht study. PloS one 2021;16(6):e0253125–. </div>
</div>
<div id="ref-Thomsen_github_1" class="csl-entry" role="listitem">
<div class="csl-left-margin">39. </div><div class="csl-right-inline">Thomsen HB. Jchr_racial_diff: Code and data repository. GitHub repository. 2023;</div>
</div>
<div id="ref-Tian2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">40. </div><div class="csl-right-inline">Tian T, Aaron RE, Kohn MA, Klonoff DC. The need for a modern error grid for clinical accuracy of blood glucose monitors and continuous glucose monitors. Journal of diabetes science and technology 2024;18(1):3–9. </div>
</div>
<div id="ref-Klonoff2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">41. </div><div class="csl-right-inline">Klonoff DC, Lias C, Vigersky R, et al. The surveillance error grid. Journal of diabetes science and technology 2014;8(4):658–72. </div>
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./2-aims.html" class="pagination-link" aria-label="Aims">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Aims</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./4-results.html" class="pagination-link" aria-label="Results">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Results</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>