## Baseline Characteristics Tables of the Datasets
The CANCAN dataset presented below was used in Study II (@tbl-baseline-cancan).
The total number of included participants were 159 and 67 (42%) had elevated NT-proBNP values.
Participants with elevated NT-proBNP tended to be older, have a longer duration of diabetes, and more frequently have cardiovascular disease. They also tended to have lower BMI and lower LDL and total cholesterol concentrations, while exhibiting modestly better overall glycemic control but slightly higher glycaemic variability.

:::  {#tbl-baseline-cancan tbl-colwidths="[40,20,20,20]" tbl-pos="H"}

| Variable | Total | NT-proBNP $\leq 125$ pg/mL | NT-proBNP >125 pg/mL |
|:---| ---:| ---:| ---:|
| N | 159 | 92 | 67 |
| Age (years) | 65 [56, 71] | 60 [53, 68] | 68 [64, 76] |
| **Sex** | | | |
| &nbsp;&nbsp;&nbsp;&nbsp;– Male | 99 (62%) | 55 (60%) | 44 (66%) |
| &nbsp;&nbsp;&nbsp;&nbsp;– Female | 60 (38%) | 37 (40%) | 23 (34%) |
| **Smoking status** | | | |
| &nbsp;&nbsp;&nbsp;&nbsp;– Never or former | 135 (85%) | 77 (84%) | 58 (87%) |
| &nbsp;&nbsp;&nbsp;&nbsp;– Current | 24 (15%) | 15 (16%) | 9 (13%) |
| Diabetes duration (years) | 16 [11, 24] | 14 [9, 22] | 19 [14, 25] |
| SCORE2-Diabetes (%) | 14.8 [9.1, 20.9] | 11.9 [7.8, 17.2] | 19.0 [13.4, 25.4] |
| HbA1c (mmol/mol) | 64 [55, 80] | 66 [56, 86] | 60 [54, 72] |
| Systolic blood pressure (mmHg) | 132 [123, 143] | 132 [123, 143] | 131 [122, 142] |
| HDL (mmol/L) | 1.0 [0.9, 1.2] | 1.0 [0.9, 1.2] | 1.0 [0.9, 1.3] |
| Total cholesterol (mmol/L) | 3.9 [3.2, 4.8] | 4.1 [3.5, 4.9] | 3.6 [3.0, 4.2] |
| eGFR (mL/min/1.73 m²) | 57 [39, 74] | 68 [52, 82] | 48 [27, 63] |
| **CGM-derived metrics** | | | |
| &nbsp;&nbsp;&nbsp;&nbsp;– CGM days (n/participant) | 13 [10, 13] | 13 [9, 13] | 13 [10, 13] |
| &nbsp;&nbsp;&nbsp;&nbsp;– Glucose management | 7.3 [6.8, 8.4] | 7.5 [6.8, 8.6] | 7.2 [6.7, 8.0] |
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; indicator (%) | | | |
| &nbsp;&nbsp;&nbsp;&nbsp;– Time in range (%) | 59.6 [31.9, 78.9] | 58.2 [20.2, 78.6] | 62.1 [40.8, 81.0] |
| &nbsp;&nbsp;&nbsp;&nbsp;– Time below range (%) | 0.0 [0.0, 1.5] | 0.0 [0.0, 0.8] | 0.2 [0.0, 2.0] |
| &nbsp;&nbsp;&nbsp;&nbsp;– Time above range (%) | 36.6 [17.6, 68.1] | 41.8 [19.8, 79.5] | 33.1 [14.1, 58.2] |
| &nbsp;&nbsp;&nbsp;&nbsp;– Coefficient of variation (%) | 27.3 [22.5, 31.9] | 25.3 [21.2, 30.3] | 28.3[24.8, 34.2] |
| &nbsp;&nbsp;&nbsp;&nbsp;– Mean amplitude of | 6.3 [5.0, 7.9] | 6.0 [4.9, 7.7] | 6.7 [5.1, 8.5] |
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; glycemic excursions (mmol/L)  | | | |

::: {.content-visible when-format="pdf"}
```{=latex}
\tablenote[0.80\linewidth]{
    Categorical values are given by number (percentage), and numerical values are given by median [interquartile range].
}
```
:::

::: {.content-visible when-format="html"}
<p style="font-size:75%">
Categorical values are given by number (percentage), and numerical values are given by median [interquartile range].
</p>
:::

Baseline table for CANCAN data.

:::
The T1DX dataset presented below was used in Study II and Study III (@tbl-baseline-t1dx).
A total of 205 participants were included, of whom 101 (49%) were White. Compared with Black participants, White participants tended to have lower HbA1c levels (63 mmol/mol vs. 72 mmol/mol ) and a higher proportion of children (49% vs. 32%). Females constituted the majority of both racial groups (54% and 60%).


::: {#tbl-baseline-t1dx tbl-colwidths="[40,20,20,20]" tbl-pos="H"}

| Characteristics | Total | Race: White | Race: Black |
|:---|---:|---:|---:|
| N | 205 | 101 | 104 |
| Race (White) | 101 (49%) | 101 (100%) | 0 (0%) |
| Sex (male) | 88 (43%) | 46 (46%) | 42 (40%) |
| Age (years) | 28 [15, 47] | 22 [13, 46] | 32 [16, 47] |
| Age group (child, < 18 yrs) | 82 (40%) | 49 (49%) | 33 (32%) |
| Age at T1D diagnosis (years) | 11 [7, 22] | 9 [6, 16] | 14 [8, 25] |
| BMI ($\text{kg/m}^2$) | 25.1 [21.7, 29.2] | 24.0 [20.7, 28.6] | 26.7 [22.3, 30.0] |
| HbA1c (mmol/mol) | 67 [57, 78] | 63 [55, 73] | 72 [60, 85] |
| **CGM-derived metrics** | | | |
| &nbsp;&nbsp;&nbsp;&nbsp;– CGM days (n/participant) | 58 [46, 69] | 63 [47, 71] | 56 [45, 66] |
| &nbsp;&nbsp;&nbsp;&nbsp;– Glucose management| 7.5 [7.0, 8.2] | 7.4 [6.9, 7.9] | 7.7 [7.0, 8.5] |
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; indicator (%) | | | |
| &nbsp;&nbsp;&nbsp;&nbsp;–  Time in range (%) | 47 [35, 57] | 49 [39, 60] | 42 [31, 54] |
| &nbsp;&nbsp;&nbsp;&nbsp;–  Time above range (%) | 45 [30, 56] | 42 [28, 53] | 48 [32, 60] |
| &nbsp;&nbsp;&nbsp;&nbsp;–  Time below range (%) | 8 [4, 14] | 6 [4, 10] | 11 [5, 15] |
| &nbsp;&nbsp;&nbsp;&nbsp;– Coefficient of variation (%) | 43.3 [39.6, 48.6] | 42.2 [38.6, 46.5] | 46.7 [40.4, 51.9] |
| &nbsp;&nbsp;&nbsp;&nbsp;– Mean amplitude of | 9.9 [8.2, 12.1] | 9.6 [8.1, 11.2] | 10.6 [8.5, 13.0] |
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; glycemic excursions (mmol/L)  | | | |

::: {.content-visible when-format="pdf"}
```{=latex}
\tablenote[0.80\linewidth]{
    Categorical values are given by number (percentage), and numerical values are given by median [interquartile range].
}
```
:::

::: {.content-visible when-format="html"}
<p style="font-size:75%">
Categorical values are given by number (percentage), and numerical values are given by median [interquartile range].
</p>
:::

Baseline table for T1DX data.

:::